### ISSUE TITLE
Complete list of pid/vids for Adafruit bootloader

### ISSUE THREAD

**Issue by kamocat** [OPEnSLab-OSU/FeatherFault#2]
I have a board with a new bootloader from Adafruit.
VID is 0x239a
PID is 0x0015

Please update the recover_fault.py script to support the new bootloader.

Normal operation, VID is 0x800b

**Comment by prototypicalpro** [comment]
Thanks for your contribution! As it turns our adafruit has a number of PID/VIDs floating around, so I'm going to reopen this issue until I've added them all.

**Comment by prototypicalpro** [comment]
Fixed in [v1.1.4](https://github.com/OPEnSLab-OSU/FeatherFault/releases/tag/v1.1.4).
